from BaseClasses import Item, ItemClassification

# base ID so we dont collide with other games
ITEM_OFFSET = 42100000

class AntonItemData:
  def __init__(self, code: int, classification: ItemClassification, quantity: int = 1):
    self.code = code
    self.classification = classification
    self.quantity = quantity

class AntonItem(Item):
  game = 'Antonblast'

# all items the game can send/receive (I HATE THIS)
item_table = {
  'Level Key: Boiler City': AntonItemData(ITEM_OFFSET + 0, ItemClassification.progression),
  'Level Key: Slowroast Sewer': AntonItemData(ITEM_OFFSET + 1, ItemClassification.progression),
  'Level Key: Brawlbuster': AntonItemData(ITEM_OFFSET + 2, ItemClassification.progression),
  'Level Key: Cinnamon Springs': AntonItemData(ITEM_OFFSET + 3, ItemClassification.progression),
  'Level Key: Bomb Candy Mines': AntonItemData(ITEM_OFFSET + 4, ItemClassification.progression),
  'Level Key: Jewel Ghoul': AntonItemData(ITEM_OFFSET + 5, ItemClassification.progression),
  'Level Key: The Big Bath': AntonItemData(ITEM_OFFSET + 6, ItemClassification.progression),
  'Level Key: Tallbuster': AntonItemData(ITEM_OFFSET + 7, ItemClassification.progression),
  'Level Key: Concrete Jungle': AntonItemData(ITEM_OFFSET + 8, ItemClassification.progression),
  'Level Key: Pinball Mire': AntonItemData(ITEM_OFFSET + 9, ItemClassification.progression),
  'Level Key: Freako Dragon': AntonItemData(ITEM_OFFSET + 10, ItemClassification.progression),
  'Level Key: The Mad Mall': AntonItemData(ITEM_OFFSET + 11, ItemClassification.progression),
  'Level Key: Smallbuster': AntonItemData(ITEM_OFFSET + 12, ItemClassification.progression),
  'Level Key: Crimson Factory': AntonItemData(ITEM_OFFSET + 13, ItemClassification.progression),
  'Level Key: Maulbuster': AntonItemData(ITEM_OFFSET + 14, ItemClassification.progression),
  'Level Key: The Mysterious Glasshouse': AntonItemData(ITEM_OFFSET + 15, ItemClassification.progression),
  'Level Key: Ring-A-Ding': AntonItemData(ITEM_OFFSET + 16, ItemClassification.progression),
  'Level Key: Devilled Gardens': AntonItemData(ITEM_OFFSET + 17, ItemClassification.progression),
  'Level Key: Hell Manor': AntonItemData(ITEM_OFFSET + 18, ItemClassification.progression),
  'Level Key: Satan': AntonItemData(ITEM_OFFSET + 19, ItemClassification.progression),
  'Level Key: Shark Tank': AntonItemData(ITEM_OFFSET + 20, ItemClassification.progression),
  'Level Key: Limes a Beach': AntonItemData(ITEM_OFFSET + 21, ItemClassification.progression),
  'Level Key: Distilled Hill': AntonItemData(ITEM_OFFSET + 22, ItemClassification.progression),
  'Level Key: Devil\'s a Beach': AntonItemData(ITEM_OFFSET + 23, ItemClassification.progression),
  'Level Key: Kaz': AntonItemData(ITEM_OFFSET + 24, ItemClassification.progression),
  'Level Key: Parrot': AntonItemData(ITEM_OFFSET + 25, ItemClassification.progression),
  'Level Key: Computer': AntonItemData(ITEM_OFFSET + 26, ItemClassification.progression),
  'Level Key: Chameleon': AntonItemData(ITEM_OFFSET + 27, ItemClassification.progression),
  'Level Key: Tag Team': AntonItemData(ITEM_OFFSET + 28, ItemClassification.progression),
  'Vinyl: Boiler City': AntonItemData(ITEM_OFFSET + 100, ItemClassification.useful),
  'Trash: TV': AntonItemData(ITEM_OFFSET + 101, ItemClassification.useful),
  'Spray: City': AntonItemData(ITEM_OFFSET + 102, ItemClassification.useful),
  'Spirit: Boiler City': AntonItemData(ITEM_OFFSET + 103, ItemClassification.progression),
  'Vinyl: Slowroast Sewer': AntonItemData(ITEM_OFFSET + 104, ItemClassification.useful),
  'Trash: Banana': AntonItemData(ITEM_OFFSET + 105, ItemClassification.useful),
  'Spray: Sewer': AntonItemData(ITEM_OFFSET + 106, ItemClassification.useful),
  'Spirit: Slowroast Sewer': AntonItemData(ITEM_OFFSET + 107, ItemClassification.progression),
  'Vinyl: Cinnamon Springs': AntonItemData(ITEM_OFFSET + 108, ItemClassification.useful),
  'Trash: Hot Chip': AntonItemData(ITEM_OFFSET + 109, ItemClassification.useful),
  'Spray: Springs': AntonItemData(ITEM_OFFSET + 110, ItemClassification.useful),
  'Spirit: Cinnamon Springs': AntonItemData(ITEM_OFFSET + 111, ItemClassification.progression),
  'Vinyl: Bomb Candy Mines': AntonItemData(ITEM_OFFSET + 112, ItemClassification.useful),
  'Trash: Mini Mitt': AntonItemData(ITEM_OFFSET + 113, ItemClassification.useful),
  'Spray: Mines': AntonItemData(ITEM_OFFSET + 114, ItemClassification.useful),
  'Spirit: Bomb Candy Mines': AntonItemData(ITEM_OFFSET + 115, ItemClassification.progression),
  'Vinyl: The Big Bath': AntonItemData(ITEM_OFFSET + 116, ItemClassification.useful),
  'Trash: Virtual Pippo': AntonItemData(ITEM_OFFSET + 117, ItemClassification.useful),
  'Spray: Bath': AntonItemData(ITEM_OFFSET + 118, ItemClassification.useful),
  'Spirit: The Big Bath': AntonItemData(ITEM_OFFSET + 119, ItemClassification.progression),
  'Vinyl: Concrete Jungle': AntonItemData(ITEM_OFFSET + 120, ItemClassification.useful),
  'Trash: Controller': AntonItemData(ITEM_OFFSET + 121, ItemClassification.useful),
  'Spray: Jungle': AntonItemData(ITEM_OFFSET + 122, ItemClassification.useful),
  'Spirit: Concrete Jungle': AntonItemData(ITEM_OFFSET + 123, ItemClassification.progression),
  'Vinyl: The Mad Mall': AntonItemData(ITEM_OFFSET + 124, ItemClassification.useful),
  'Trash: Ballble Tea': AntonItemData(ITEM_OFFSET + 125, ItemClassification.useful),
  'Spray: Mall': AntonItemData(ITEM_OFFSET + 126, ItemClassification.useful),
  'Spirit: The Mad Mall': AntonItemData(ITEM_OFFSET + 127, ItemClassification.progression),
  'Vinyl: Pinball Mire': AntonItemData(ITEM_OFFSET + 128, ItemClassification.useful),
  'Trash: Bottle Cap': AntonItemData(ITEM_OFFSET + 129, ItemClassification.useful),
  'Spray: Mire': AntonItemData(ITEM_OFFSET + 130, ItemClassification.useful),
  'Spirit: Pinball Mire': AntonItemData(ITEM_OFFSET + 131, ItemClassification.progression),
  'Vinyl: Crimson Factory': AntonItemData(ITEM_OFFSET + 132, ItemClassification.useful),
  'Trash: Car': AntonItemData(ITEM_OFFSET + 133, ItemClassification.useful),
  'Spray: Factory': AntonItemData(ITEM_OFFSET + 134, ItemClassification.useful),
  'Spirit: Crimson Factory': AntonItemData(ITEM_OFFSET + 135, ItemClassification.progression),
  'Vinyl: The Mysterious Glasshouse': AntonItemData(ITEM_OFFSET + 136, ItemClassification.useful),
  'Trash: Trophy': AntonItemData(ITEM_OFFSET + 137, ItemClassification.useful),
  'Spray: Glasshouse': AntonItemData(ITEM_OFFSET + 138, ItemClassification.useful),
  'Spirit: The Mysterious Glasshouse': AntonItemData(ITEM_OFFSET + 139, ItemClassification.progression),
  'Vinyl: Devilled Gardens': AntonItemData(ITEM_OFFSET + 140, ItemClassification.useful),
  'Trash: Headphones': AntonItemData(ITEM_OFFSET + 141, ItemClassification.useful),
  'Spray: Gardens': AntonItemData(ITEM_OFFSET + 142, ItemClassification.useful),
  'Spirit: Devilled Gardens': AntonItemData(ITEM_OFFSET + 143, ItemClassification.progression),
  'Vinyl: Hell Manor': AntonItemData(ITEM_OFFSET + 144, ItemClassification.useful),
  'Trash: Tallbuster': AntonItemData(ITEM_OFFSET + 145, ItemClassification.useful),
  'Spray: Manor': AntonItemData(ITEM_OFFSET + 146, ItemClassification.useful),
  'Spirit: Hell Manor': AntonItemData(ITEM_OFFSET + 147, ItemClassification.progression),
  'Boss Spirit: Brawlbuster': AntonItemData(ITEM_OFFSET + 200, ItemClassification.progression),
  'Boss Spirit: Jewel Ghoul': AntonItemData(ITEM_OFFSET + 201, ItemClassification.progression),
  'Boss Spirit: Tallbuster': AntonItemData(ITEM_OFFSET + 202, ItemClassification.progression),
  'Boss Spirit: Freako Dragon': AntonItemData(ITEM_OFFSET + 203, ItemClassification.progression),
  'Boss Spirit: Smallbuster': AntonItemData(ITEM_OFFSET + 204, ItemClassification.progression),
  'Boss Spirit: Maulbuster': AntonItemData(ITEM_OFFSET + 205, ItemClassification.progression),
  'Boss Spirit: Ring-A-Ding': AntonItemData(ITEM_OFFSET + 206, ItemClassification.progression),
  'Boss Spirit: Satan': AntonItemData(ITEM_OFFSET + 207, ItemClassification.useful),
  'Prize Star: Kaz': AntonItemData(ITEM_OFFSET + 208, ItemClassification.useful),
  'Prize Star: Parrot': AntonItemData(ITEM_OFFSET + 209, ItemClassification.useful),
  'Prize Star: Computer': AntonItemData(ITEM_OFFSET + 210, ItemClassification.useful),
  'Prize Star: Chameleon': AntonItemData(ITEM_OFFSET + 211, ItemClassification.useful),
  'Prize Ribbon: Tag Team': AntonItemData(ITEM_OFFSET + 212, ItemClassification.useful),
  'Souvenir: Shark Tank': AntonItemData(ITEM_OFFSET + 213, ItemClassification.useful),
  'Souvenir: Limes a Beach': AntonItemData(ITEM_OFFSET + 214, ItemClassification.useful),
  'Souvenir: Distilled Hill': AntonItemData(ITEM_OFFSET + 215, ItemClassification.useful),
  'Souvenir: Devil\'s a Beach': AntonItemData(ITEM_OFFSET + 216, ItemClassification.useful),
  'HP Beet Up': AntonItemData(ITEM_OFFSET + 300, ItemClassification.useful),
  'Bonus HP Up': AntonItemData(ITEM_OFFSET + 301, ItemClassification.useful),
  'Balloon Add-On': AntonItemData(ITEM_OFFSET + 302, ItemClassification.useful),
  'Pet Add-On': AntonItemData(ITEM_OFFSET + 303, ItemClassification.useful),
  'Spirit Timer Add-On': AntonItemData(ITEM_OFFSET + 304, ItemClassification.useful),
  'Trinket: Shutter Shades': AntonItemData(ITEM_OFFSET + 305, ItemClassification.useful),
  'Trinket: Cowboy Hat': AntonItemData(ITEM_OFFSET + 306, ItemClassification.useful),
  'Trinket: Funny TV': AntonItemData(ITEM_OFFSET + 307, ItemClassification.useful),
  'Trinket: Funny TV Big': AntonItemData(ITEM_OFFSET + 308, ItemClassification.useful),
  'Trinket: Pet Color': AntonItemData(ITEM_OFFSET + 309, ItemClassification.useful),
  'Screen Palette: VB': AntonItemData(ITEM_OFFSET + 310, ItemClassification.useful),
  'Screen Palette: GB': AntonItemData(ITEM_OFFSET + 311, ItemClassification.useful),
  'Shop Vinyl: Collen Cyte': AntonItemData(ITEM_OFFSET + 312, ItemClassification.useful),
  'Shop Vinyl: Element 27': AntonItemData(ITEM_OFFSET + 313, ItemClassification.useful),
  'Shop Vinyl: Fred Fuchs': AntonItemData(ITEM_OFFSET + 314, ItemClassification.useful),
  'Shop Vinyl: Joseph Cassin': AntonItemData(ITEM_OFFSET + 315, ItemClassification.useful),
  'Shop Vinyl: Logan Gerrol': AntonItemData(ITEM_OFFSET + 316, ItemClassification.useful),
  'Shop Vinyl: Pear Basket': AntonItemData(ITEM_OFFSET + 317, ItemClassification.useful),
  'Shop Vinyl: Rom M': AntonItemData(ITEM_OFFSET + 318, ItemClassification.useful),
  'Shop Vinyl: Impetus': AntonItemData(ITEM_OFFSET + 319, ItemClassification.useful),
  'Shop Vinyl: William': AntonItemData(ITEM_OFFSET + 320, ItemClassification.useful),

  'Small Coins': AntonItemData(ITEM_OFFSET + 400, ItemClassification.filler),
  'Large Coins': AntonItemData(ITEM_OFFSET + 401, ItemClassification.filler),
  'Jackpot Coins': AntonItemData(ITEM_OFFSET + 402, ItemClassification.filler),
}

item_groups = {
  'keys': [n for n in item_table if n.startswith('Level Key:')],
  'collectibles': [n for n in item_table if any(n.startswith(x) for x in ['Vinyl:', 'Trash:', 'Spray:', 'Spirit:', 'Souvenir:', 'Prize'])],
  'upgrades': [n for n in item_table if any(n.startswith(x) for x in ['HP', 'Bonus', 'Balloon', 'Pet', 'Spirit Timer'])],
  'trinkets': [n for n in item_table if n.startswith('Trinket:') or n.startswith('Screen Palette:')],
  'shop_vinyls': [n for n in item_table if n.startswith('Shop Vinyl:')],
  'coins': ['Small Coins', 'Large Coins', 'Jackpot Coins'],
  'skins': [],
}